import Head from 'next/head';
import { Button } from 'antd';
import Header from '../components/Header';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>my_blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header />
      <main className={styles.main}>
       <Button>main</Button>
      </main>

      <footer className={styles.footer}>
       footer
      </footer>
    </div>
  )
}
